nombre = input("Ingresa tu nombre: ")
edad = input("Ingresa tu edad: ")
ciudad = input("Ingresa tu ciudad de residencia: ")
trabajo = input("Ingresa tu ocupación o trabajo: ")
estudio = input("Ingresa tu área de estudio o especialización: ")
pais = input("si pudieras viajar a cualquier pais, ¿a cual irias? ")


print("\n-----------------------------------------")
print(f"¡Hola, soy {nombre}!, tengo {edad} años y vivo en {ciudad}.")
print(f"Actualmente, trabajo como {trabajo}.")
print(f"Además, estudio {estudio} para mejorar mis habilidades y conocimientos,")
print("me encanta aprender cosas nuevas y enfrentar nuevos desafíos cada día.")
print("Mi sueño es poder viajar por todo el mundo y conocer nuevas culturas,")
print(f"aunque si pudiera escoger ya mismo, iria a {pais}")